# Generated by Django 6.0.5 on 2026-05-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_task_subtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='previous_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В процессе'), ('done', 'Выполнена'), ('closed', 'Закрыта')], default='new', max_length=20),
        ),
    ]
